FROM pypy:3.9-slim-buster as builder

COPY ./app/requirements.txt /opt/app/
RUN pip install --no-cache-dir --upgrade -r /opt/app/requirements.txt

COPY ./app /opt/app

FROM pypy:3.9-slim-buster as runner

ARG USERNAME="fastapi"
ARG GROUPNAME="fastapi"
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID $GROUPNAME && \
    useradd -m -s /bin/bash -u $UID -g $GID $USERNAME

COPY --from=builder --chown=$USERNAME:$GROUPNAME /opt/app /opt/app
COPY --from=builder /opt/pypy/lib/pypy3.9/site-packages/ /opt/pypy/lib/pypy3.9/site-packages/

ENV PYTHONPATH "${PYTHONPATH}:/opt/app"

RUN apt-get update \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app
USER $USERNAME
