FROM pypy:3.9-slim-buster

COPY ./app/requirements.txt /opt/app/requirements.txt
RUN pypy -m pip install -U pip && pypy -m pip install --no-cache-dir --upgrade -r /opt/app/requirements.txt

ARG USERNAME="fastapi"
ARG GROUPNAME="fastapi"
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID $GROUPNAME && \
    useradd -m -s /bin/bash -u $UID -g $GID $USERNAME

COPY --chown=$USERNAME:$GROUPNAME ./app /opt/app
WORKDIR /opt/app

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update && apt-get clean -y && rm -rf /var/lib/apt/lists/*

USER $USERNAME